name: Check SonarQube Server Accessibility

on:
  push:
    branches:
      - main
jobs:
  wget_check:
    runs-on: self-hosted
    steps:
      - name: Check SonarQube server with wget
        run: |
          wget --spider http://localhost:9000
